version: "3.9"
services:
  backend:
    build: ./server
    container_name: calendly-backend
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
  frontend:
    build:
      context: .
      args:
        # El frontend, ya compilado, hará fetch a esta URL desde el navegador
        - VITE_API_BASE=http://localhost:3001
    container_name: calendly-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend